/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NewProjectRouteImport } from './routes/new-project'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIdProjectIdRouteImport } from './routes/$userId/$projectId'
import { Route as UserIdProjectIdEditProjectRouteImport } from './routes/$userId/$projectId/edit-project'
import { Route as UserIdProjectIdAddTimeRouteImport } from './routes/$userId/$projectId/add-time'
import { Route as UserIdProjectIdLogIdEditTimeRouteImport } from './routes/$userId/$projectId/$logId/edit-time'
import { Route as UserIdProjectIdLogIdAddNewTimeRouteImport } from './routes/$userId/$projectId/$logId/add-new-time'

const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewProjectRoute = NewProjectRouteImport.update({
  id: '/new-project',
  path: '/new-project',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdProjectIdRoute = UserIdProjectIdRouteImport.update({
  id: '/$userId/$projectId',
  path: '/$userId/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdProjectIdEditProjectRoute =
  UserIdProjectIdEditProjectRouteImport.update({
    id: '/edit-project',
    path: '/edit-project',
    getParentRoute: () => UserIdProjectIdRoute,
  } as any)
const UserIdProjectIdAddTimeRoute = UserIdProjectIdAddTimeRouteImport.update({
  id: '/add-time',
  path: '/add-time',
  getParentRoute: () => UserIdProjectIdRoute,
} as any)
const UserIdProjectIdLogIdEditTimeRoute =
  UserIdProjectIdLogIdEditTimeRouteImport.update({
    id: '/$logId/edit-time',
    path: '/$logId/edit-time',
    getParentRoute: () => UserIdProjectIdRoute,
  } as any)
const UserIdProjectIdLogIdAddNewTimeRoute =
  UserIdProjectIdLogIdAddNewTimeRouteImport.update({
    id: '/$logId/add-new-time',
    path: '/$logId/add-new-time',
    getParentRoute: () => UserIdProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new-project': typeof NewProjectRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset': typeof ResetRoute
  '/$userId/$projectId': typeof UserIdProjectIdRouteWithChildren
  '/$userId/$projectId/add-time': typeof UserIdProjectIdAddTimeRoute
  '/$userId/$projectId/edit-project': typeof UserIdProjectIdEditProjectRoute
  '/$userId/$projectId/$logId/add-new-time': typeof UserIdProjectIdLogIdAddNewTimeRoute
  '/$userId/$projectId/$logId/edit-time': typeof UserIdProjectIdLogIdEditTimeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new-project': typeof NewProjectRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset': typeof ResetRoute
  '/$userId/$projectId': typeof UserIdProjectIdRouteWithChildren
  '/$userId/$projectId/add-time': typeof UserIdProjectIdAddTimeRoute
  '/$userId/$projectId/edit-project': typeof UserIdProjectIdEditProjectRoute
  '/$userId/$projectId/$logId/add-new-time': typeof UserIdProjectIdLogIdAddNewTimeRoute
  '/$userId/$projectId/$logId/edit-time': typeof UserIdProjectIdLogIdEditTimeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new-project': typeof NewProjectRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset': typeof ResetRoute
  '/$userId/$projectId': typeof UserIdProjectIdRouteWithChildren
  '/$userId/$projectId/add-time': typeof UserIdProjectIdAddTimeRoute
  '/$userId/$projectId/edit-project': typeof UserIdProjectIdEditProjectRoute
  '/$userId/$projectId/$logId/add-new-time': typeof UserIdProjectIdLogIdAddNewTimeRoute
  '/$userId/$projectId/$logId/edit-time': typeof UserIdProjectIdLogIdEditTimeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/new-project'
    | '/profile'
    | '/register'
    | '/reset'
    | '/$userId/$projectId'
    | '/$userId/$projectId/add-time'
    | '/$userId/$projectId/edit-project'
    | '/$userId/$projectId/$logId/add-new-time'
    | '/$userId/$projectId/$logId/edit-time'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/new-project'
    | '/profile'
    | '/register'
    | '/reset'
    | '/$userId/$projectId'
    | '/$userId/$projectId/add-time'
    | '/$userId/$projectId/edit-project'
    | '/$userId/$projectId/$logId/add-new-time'
    | '/$userId/$projectId/$logId/edit-time'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/new-project'
    | '/profile'
    | '/register'
    | '/reset'
    | '/$userId/$projectId'
    | '/$userId/$projectId/add-time'
    | '/$userId/$projectId/edit-project'
    | '/$userId/$projectId/$logId/add-new-time'
    | '/$userId/$projectId/$logId/edit-time'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  NewProjectRoute: typeof NewProjectRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetRoute: typeof ResetRoute
  UserIdProjectIdRoute: typeof UserIdProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-project': {
      id: '/new-project'
      path: '/new-project'
      fullPath: '/new-project'
      preLoaderRoute: typeof NewProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$userId/$projectId': {
      id: '/$userId/$projectId'
      path: '/$userId/$projectId'
      fullPath: '/$userId/$projectId'
      preLoaderRoute: typeof UserIdProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$userId/$projectId/edit-project': {
      id: '/$userId/$projectId/edit-project'
      path: '/edit-project'
      fullPath: '/$userId/$projectId/edit-project'
      preLoaderRoute: typeof UserIdProjectIdEditProjectRouteImport
      parentRoute: typeof UserIdProjectIdRoute
    }
    '/$userId/$projectId/add-time': {
      id: '/$userId/$projectId/add-time'
      path: '/add-time'
      fullPath: '/$userId/$projectId/add-time'
      preLoaderRoute: typeof UserIdProjectIdAddTimeRouteImport
      parentRoute: typeof UserIdProjectIdRoute
    }
    '/$userId/$projectId/$logId/edit-time': {
      id: '/$userId/$projectId/$logId/edit-time'
      path: '/$logId/edit-time'
      fullPath: '/$userId/$projectId/$logId/edit-time'
      preLoaderRoute: typeof UserIdProjectIdLogIdEditTimeRouteImport
      parentRoute: typeof UserIdProjectIdRoute
    }
    '/$userId/$projectId/$logId/add-new-time': {
      id: '/$userId/$projectId/$logId/add-new-time'
      path: '/$logId/add-new-time'
      fullPath: '/$userId/$projectId/$logId/add-new-time'
      preLoaderRoute: typeof UserIdProjectIdLogIdAddNewTimeRouteImport
      parentRoute: typeof UserIdProjectIdRoute
    }
  }
}

interface UserIdProjectIdRouteChildren {
  UserIdProjectIdAddTimeRoute: typeof UserIdProjectIdAddTimeRoute
  UserIdProjectIdEditProjectRoute: typeof UserIdProjectIdEditProjectRoute
  UserIdProjectIdLogIdAddNewTimeRoute: typeof UserIdProjectIdLogIdAddNewTimeRoute
  UserIdProjectIdLogIdEditTimeRoute: typeof UserIdProjectIdLogIdEditTimeRoute
}

const UserIdProjectIdRouteChildren: UserIdProjectIdRouteChildren = {
  UserIdProjectIdAddTimeRoute: UserIdProjectIdAddTimeRoute,
  UserIdProjectIdEditProjectRoute: UserIdProjectIdEditProjectRoute,
  UserIdProjectIdLogIdAddNewTimeRoute: UserIdProjectIdLogIdAddNewTimeRoute,
  UserIdProjectIdLogIdEditTimeRoute: UserIdProjectIdLogIdEditTimeRoute,
}

const UserIdProjectIdRouteWithChildren = UserIdProjectIdRoute._addFileChildren(
  UserIdProjectIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  NewProjectRoute: NewProjectRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetRoute: ResetRoute,
  UserIdProjectIdRoute: UserIdProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
