/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NewProjectRouteImport } from './routes/new-project'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIdRouteImport } from './routes/project/$id'
import { Route as ProjectIdEditTimeRouteImport } from './routes/project/$id/edit-time'
import { Route as ProjectIdEditProjectRouteImport } from './routes/project/$id/edit-project'
import { Route as ProjectIdAddTimeRouteImport } from './routes/project/$id/add-time'
import { Route as ProjectIdAddNewTimeRouteImport } from './routes/project/$id/add-new-time'

const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewProjectRoute = NewProjectRouteImport.update({
  id: '/new-project',
  path: '/new-project',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdEditTimeRoute = ProjectIdEditTimeRouteImport.update({
  id: '/edit-time',
  path: '/edit-time',
  getParentRoute: () => ProjectIdRoute,
} as any)
const ProjectIdEditProjectRoute = ProjectIdEditProjectRouteImport.update({
  id: '/edit-project',
  path: '/edit-project',
  getParentRoute: () => ProjectIdRoute,
} as any)
const ProjectIdAddTimeRoute = ProjectIdAddTimeRouteImport.update({
  id: '/add-time',
  path: '/add-time',
  getParentRoute: () => ProjectIdRoute,
} as any)
const ProjectIdAddNewTimeRoute = ProjectIdAddNewTimeRouteImport.update({
  id: '/add-new-time',
  path: '/add-new-time',
  getParentRoute: () => ProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new-project': typeof NewProjectRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset': typeof ResetRoute
  '/project/$id': typeof ProjectIdRouteWithChildren
  '/project/$id/add-new-time': typeof ProjectIdAddNewTimeRoute
  '/project/$id/add-time': typeof ProjectIdAddTimeRoute
  '/project/$id/edit-project': typeof ProjectIdEditProjectRoute
  '/project/$id/edit-time': typeof ProjectIdEditTimeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new-project': typeof NewProjectRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset': typeof ResetRoute
  '/project/$id': typeof ProjectIdRouteWithChildren
  '/project/$id/add-new-time': typeof ProjectIdAddNewTimeRoute
  '/project/$id/add-time': typeof ProjectIdAddTimeRoute
  '/project/$id/edit-project': typeof ProjectIdEditProjectRoute
  '/project/$id/edit-time': typeof ProjectIdEditTimeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new-project': typeof NewProjectRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset': typeof ResetRoute
  '/project/$id': typeof ProjectIdRouteWithChildren
  '/project/$id/add-new-time': typeof ProjectIdAddNewTimeRoute
  '/project/$id/add-time': typeof ProjectIdAddTimeRoute
  '/project/$id/edit-project': typeof ProjectIdEditProjectRoute
  '/project/$id/edit-time': typeof ProjectIdEditTimeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/new-project'
    | '/profile'
    | '/register'
    | '/reset'
    | '/project/$id'
    | '/project/$id/add-new-time'
    | '/project/$id/add-time'
    | '/project/$id/edit-project'
    | '/project/$id/edit-time'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/new-project'
    | '/profile'
    | '/register'
    | '/reset'
    | '/project/$id'
    | '/project/$id/add-new-time'
    | '/project/$id/add-time'
    | '/project/$id/edit-project'
    | '/project/$id/edit-time'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/new-project'
    | '/profile'
    | '/register'
    | '/reset'
    | '/project/$id'
    | '/project/$id/add-new-time'
    | '/project/$id/add-time'
    | '/project/$id/edit-project'
    | '/project/$id/edit-time'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  NewProjectRoute: typeof NewProjectRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetRoute: typeof ResetRoute
  ProjectIdRoute: typeof ProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-project': {
      id: '/new-project'
      path: '/new-project'
      fullPath: '/new-project'
      preLoaderRoute: typeof NewProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id': {
      id: '/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id/edit-time': {
      id: '/project/$id/edit-time'
      path: '/edit-time'
      fullPath: '/project/$id/edit-time'
      preLoaderRoute: typeof ProjectIdEditTimeRouteImport
      parentRoute: typeof ProjectIdRoute
    }
    '/project/$id/edit-project': {
      id: '/project/$id/edit-project'
      path: '/edit-project'
      fullPath: '/project/$id/edit-project'
      preLoaderRoute: typeof ProjectIdEditProjectRouteImport
      parentRoute: typeof ProjectIdRoute
    }
    '/project/$id/add-time': {
      id: '/project/$id/add-time'
      path: '/add-time'
      fullPath: '/project/$id/add-time'
      preLoaderRoute: typeof ProjectIdAddTimeRouteImport
      parentRoute: typeof ProjectIdRoute
    }
    '/project/$id/add-new-time': {
      id: '/project/$id/add-new-time'
      path: '/add-new-time'
      fullPath: '/project/$id/add-new-time'
      preLoaderRoute: typeof ProjectIdAddNewTimeRouteImport
      parentRoute: typeof ProjectIdRoute
    }
  }
}

interface ProjectIdRouteChildren {
  ProjectIdAddNewTimeRoute: typeof ProjectIdAddNewTimeRoute
  ProjectIdAddTimeRoute: typeof ProjectIdAddTimeRoute
  ProjectIdEditProjectRoute: typeof ProjectIdEditProjectRoute
  ProjectIdEditTimeRoute: typeof ProjectIdEditTimeRoute
}

const ProjectIdRouteChildren: ProjectIdRouteChildren = {
  ProjectIdAddNewTimeRoute: ProjectIdAddNewTimeRoute,
  ProjectIdAddTimeRoute: ProjectIdAddTimeRoute,
  ProjectIdEditProjectRoute: ProjectIdEditProjectRoute,
  ProjectIdEditTimeRoute: ProjectIdEditTimeRoute,
}

const ProjectIdRouteWithChildren = ProjectIdRoute._addFileChildren(
  ProjectIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  NewProjectRoute: NewProjectRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetRoute: ResetRoute,
  ProjectIdRoute: ProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
